version: '3'

services:
  wikidb:
    image: postgres:15
    container_name: uksf-wiki-db
    restart: always
    environment:
      POSTGRES_DB: wikijs
      POSTGRES_USER: wikijs
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/db:/var/lib/postgresql/data

  wiki:
    image: ghcr.io/requarks/wiki:2
    container_name: uksf-wiki
    restart: always
    depends_on:
      - wikidb
    ports:
      - "3000:3000"
    environment:
      DB_TYPE: postgres
      DB_HOST: wikidb
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: ${DB_PASSWORD}
      DB_NAME: wikijs
      LOG_LEVEL: info
    volumes:
      - ./data/wiki:/wiki/data

networks:
  default:
    driver: bridge
